// This file is generated by TypeScript compilation
// The actual server code is in src/server.ts and compiled to dist/server.js
// For deployment, we use the compiled version

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const distServerPath = path.join(__dirname, 'dist', 'server.js');

console.log('🔍 Checking for compiled server at:', distServerPath);

if (!fs.existsSync(distServerPath)) {
  console.log('❌ Compiled server not found, running build...');
  try {
    // Run TypeScript compilation
    execSync('npm run build', { stdio: 'inherit', cwd: __dirname });
    console.log('✅ Build completed successfully');
  } catch (error) {
    console.error('❌ Build failed:', error.message);
    process.exit(1);
  }
}

// Check again after build
if (fs.existsSync(distServerPath)) {
  console.log('✅ Loading compiled server...');
  module.exports = require('./dist/server.js');
} else {
  console.error('❌ Compiled server still not found at:', distServerPath);
  console.error('❌ Please check TypeScript compilation');
  process.exit(1);
}
