import { useState, useEffect } from 'react'
import { Input } from '../components/ui/input'
import { useAuthStore } from '../store/authStore'
import { Youtube, Video, Zap, Target, BookOpen, X } from 'lucide-react'
import '../styles/animations.css'

export default function YoutubeSummarizer() {
  const [videoUrl, setVideoUrl] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)
  const [summary, setSummary] = useState('')
  const [videoInfo, setVideoInfo] = useState<any>(null)
  const [mounted, setMounted] = useState(false)
  const { token } = useAuthStore()

  // Initialize animations
  useEffect(() => {
    setMounted(true)
  }, [])

  const handleSummarize = async () => {
    if (!videoUrl || !videoUrl.trim()) {
      setSummary('Please enter a valid YouTube URL.')
      return
    }
    
    setIsProcessing(true)
    setSummary('')
    
    try {
      // Extract video ID from YouTube URL
      const videoId = extractVideoId(videoUrl.trim())
      if (!videoId) {
        setSummary('Invalid YouTube URL. Please enter a valid YouTube video URL.')
        return
      }

      // Simulate API call to get video info and summary
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      // Mock video info
      setVideoInfo({
        title: "Introduction to Machine Learning",
        channel: "AI Education",
        duration: "15:42",
        thumbnail: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`
      })

      // Mock summary
      setSummary(`This video provides a comprehensive introduction to machine learning concepts. 

Key topics covered:
• What is Machine Learning and its applications
• Types of ML: Supervised, Unsupervised, and Reinforcement Learning
• Common algorithms and their use cases
• Real-world examples and implementations
• Future trends and career opportunities in ML

The presenter explains complex concepts in simple terms, making it accessible for beginners while providing enough depth for those with some programming background. The video includes practical examples and visual demonstrations to help viewers understand the core principles.

Overall, this is an excellent starting point for anyone looking to understand the fundamentals of machine learning and its growing importance in today's technology landscape.`)

    } catch (error) {
      setSummary('Error processing video. Please try again.')
    } finally {
      setIsProcessing(false)
    }
  }

  const extractVideoId = (url: string) => {
    if (!url || typeof url !== 'string') return null
    
    const trimmedUrl = url.trim()
    const patterns = [
      /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/)([^&\n?#]+)/,
      /youtube\.com\/watch\?.*v=([^&\n?#]+)/,
      /^([^&\n?#]{11})$/ // Direct video ID
    ]
    
    for (const pattern of patterns) {
      const match = trimmedUrl.match(pattern)
      if (match && match[1] && match[1].length === 11) {
        return match[1]
      }
    }
    return null
  }

  const handleCopySummary = () => {
    if (!summary) return
    
    navigator.clipboard.writeText(summary).then(() => {
      // Show success feedback
      const button = document.querySelector('[data-action="copy"]')
      if (button) {
        const originalText = button.textContent
        button.textContent = '✓ Copied!'
        button.classList.add('bg-green-500', 'text-white', 'border-green-500')
        
        setTimeout(() => {
          button.textContent = originalText
          button.classList.remove('bg-green-500', 'text-white', 'border-green-500')
        }, 2000)
      }
    }).catch(err => {
      console.error('Failed to copy text: ', err)
    })
  }

  const handleSaveSummary = () => {
    if (!summary || !videoInfo) return
    
    // Create a downloadable text file
    const content = `YouTube Video Summary\n\nTitle: ${videoInfo.title}\nChannel: ${videoInfo.channel}\nDuration: ${videoInfo.duration}\n\nSummary:\n${summary}\n\nGenerated by MyLearn AI Tutor - ${new Date().toLocaleDateString()}`
    
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    
    const a = document.createElement('a')
    a.href = url
    a.download = `${videoInfo.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_summary.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    // Show success feedback
    const button = document.querySelector('[data-action="save"]')
    if (button) {
      const originalText = button.textContent
      button.textContent = '✓ Saved!'
      button.classList.add('bg-green-500', 'text-white', 'border-green-500')
      
      setTimeout(() => {
        button.textContent = originalText
        button.classList.remove('bg-green-500', 'text-white', 'border-green-500')
      }, 2000)
    }
  }

  const handleShareSummary = () => {
    if (!summary || !videoInfo) return
    
    // Create shareable content
    const shareText = `Check out this summary of "${videoInfo.title}" from ${videoInfo.channel}:\n\n${summary.substring(0, 200)}...\n\nGenerated by MyLearn AI Tutor`
    
    if (navigator.share) {
      // Use Web Share API if available
      navigator.share({
        title: `Video Summary: ${videoInfo.title}`,
        text: shareText,
        url: window.location.href
      }).catch(err => {
        console.log('Share cancelled or failed:', err)
        // Fallback to copying to clipboard
        handleCopySummary()
      })
    } else {
      // Fallback: copy share text to clipboard
      navigator.clipboard.writeText(shareText).then(() => {
        const button = document.querySelector('[data-action="share"]')
        if (button) {
          const originalText = button.textContent
          button.textContent = '✓ Link Copied!'
          button.classList.add('bg-green-500', 'text-white', 'border-green-500')
          
          setTimeout(() => {
            button.textContent = originalText
            button.classList.remove('bg-green-500', 'text-white', 'border-green-500')
          }, 2000)
        }
      })
    }
  }

  const handleClear = () => {
    setVideoUrl('')
    setSummary('')
    setVideoInfo(null)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-900 relative overflow-hidden">
      {/* Enhanced animated background with glass effect */}
      <div className="absolute inset-0 overflow-hidden">
        {/* Layer 1: Enhanced floating orbs with glass effect */}
        <div className="absolute top-20 left-20 w-64 h-64 bg-gradient-to-r from-blue-400/30 to-purple-400/30 rounded-full mix-blend-screen filter blur-3xl opacity-40 animate-float"></div>
        <div className="absolute top-40 right-20 w-64 h-64 bg-gradient-to-r from-pink-400/30 to-red-400/30 rounded-full mix-blend-screen filter blur-3xl opacity-40 animate-float" 
             style={{ animationDelay: '2s' }}></div>
        <div className="absolute bottom-20 left-1/2 w-64 h-64 bg-gradient-to-r from-green-400/30 to-blue-400/30 rounded-full mix-blend-screen filter blur-3xl opacity-40 animate-float" 
             style={{ animationDelay: '4s' }}></div>
        
        {/* Layer 2: Enhanced glass gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-black/10 via-transparent to-transparent"></div>
        
        {/* Layer 3: Enhanced floating glass particles */}
        {[...Array(15)].map((_, i) => (
          <div
            key={i}
            className="absolute bg-white/20 rounded-full animate-float"
            style={{
              width: `${Math.random() * 4 + 1}px`,
              height: `${Math.random() * 4 + 1}px`,
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
              animationDelay: `${Math.random() * 5}s`,
              animationDuration: `${15 + Math.random() * 10}s`
            }}
          />
        ))}
      </div>
      
      <main className="max-w-6xl mx-auto px-6 py-8 relative z-10" style={{paddingTop: '100px'}}>
        {/* Hero Section with Enhanced Glassmorphism */}
        <div className={`text-center mb-12 transform transition-all duration-1000 ${mounted ? 'translate-y-0 opacity-100' : '-translate-y-10 opacity-0'}`}>
          <div className="backdrop-blur-3xl bg-white/6 border border-white/20 rounded-3xl p-8 text-white shadow-2xl mb-8 relative overflow-hidden group hover:bg-white/10 transition-all duration-500">
            {/* Enhanced glass gradient background */}
            <div className="absolute inset-0 bg-gradient-to-r from-purple-600/20 via-indigo-600/20 to-pink-600/20 opacity-0 group-hover:opacity-60 transition-opacity duration-500" />
            <div className="absolute inset-0 bg-gradient-to-t from-white/5 via-transparent to-white/5 opacity-100" />
            
            {/* Content */}
            <div className="relative z-10">
              <div className="flex items-center justify-center mb-6">
                <div className="relative">
                  <Youtube className="w-16 h-16 text-red-400" />
                  <div className="absolute -inset-2 bg-red-400/30 rounded-full blur-xl animate-pulse"></div>
                </div>
                <h1 className="text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white via-blue-200 to-purple-200 ml-4">
                  YouTube Video Summarizer
                </h1>
              </div>
              <p className="text-xl text-white/90 max-w-3xl mx-auto leading-relaxed">
                Transform any YouTube video into concise, easy-to-read summaries. 
                Get key insights without watching the entire video.
              </p>
              <div className="flex items-center justify-center space-x-8 mt-8">
                {[
                  { icon: Zap, text: 'Lightning Fast', delay: '0s' },
                  { icon: Target, text: 'Accurate Insights', delay: '0.1s' },
                  { icon: BookOpen, text: 'Study Friendly', delay: '0.2s' }
                ].map((feature, index) => (
                  <div 
                    key={index}
                    className="flex items-center space-x-2 opacity-0 animate-fade-in-up backdrop-blur-xl bg-white/8 px-4 py-2 rounded-full border border-white/20 hover:bg-white/15 transition-all duration-300"
                    style={{ animationDelay: feature.delay }}
                  >
                    <feature.icon className="w-6 h-6 text-blue-300" />
                    <span className="text-white/90 font-medium">{feature.text}</span>
                  </div>
                ))}
              </div>
            </div>
            
            {/* Enhanced glass decorative elements */}
            <div className="absolute top-4 right-4 w-16 h-16 bg-white/10 rounded-full animate-pulse backdrop-blur-sm" />
            <div className="absolute bottom-4 left-4 w-12 h-12 bg-white/10 rounded-full animate-pulse backdrop-blur-sm" style={{ animationDelay: '1s' }} />
          </div>
        </div>

        <div className="flex flex-col lg:flex-row gap-8 items-stretch">
          {/* Left Column - Input Section with Enhanced Glass */}
          <div className={`flex-1 transform transition-all duration-1000 ${mounted ? 'translate-x-0 opacity-100' : '-translate-x-10 opacity-0'}`}>
            <div className="backdrop-blur-3xl bg-white/5 border border-white/25 rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-500 transform hover:scale-[1.02] overflow-hidden group relative h-full">
              {/* Enhanced glass border gradient */}
              <div className="absolute inset-0 bg-gradient-to-r from-purple-500/30 to-indigo-500/30 rounded-3xl opacity-0 group-hover:opacity-40 transition-opacity duration-500" />
              <div className="absolute inset-0 bg-gradient-to-t from-white/10 via-transparent to-white/5 opacity-100" />
              
              <div className="p-8 relative z-10 flex flex-col h-full justify-center">
                <div className="flex items-center mb-8">
                  <div className="w-12 h-12 bg-gradient-to-br from-red-500/90 to-pink-500/90 rounded-xl flex items-center justify-center mr-4 shadow-xl backdrop-blur-xl border border-white/30">
                    <Video className="w-7 h-7 text-white" />
                  </div>
                  <div>
                    <h2 className="text-3xl font-bold bg-gradient-to-r from-gray-100 to-gray-300 bg-clip-text text-transparent">Video URL</h2>
                    <p className="text-white/80 mt-1">Enter any YouTube video link</p>
                  </div>
                </div>
                
                <div className="space-y-6">
                  <div className="relative group/input">
                    <div className="absolute inset-0 bg-gradient-to-r from-purple-500/30 to-indigo-500/30 rounded-2xl opacity-0 group-hover/input:opacity-25 transition-opacity duration-300" />
                    <Input
                      type="url"
                      placeholder="https://www.youtube.com/watch?v=..."
                      value={videoUrl}
                      onChange={(e) => setVideoUrl(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && !isProcessing && handleSummarize()}
                      className="w-full px-6 py-5 border-2 border-white/25 rounded-2xl focus:outline-none focus:ring-4 focus:ring-purple-500/40 focus:border-purple-400 text-lg font-medium transition-all duration-300 bg-white/10 backdrop-blur-xl relative z-10 placeholder-white/60 text-white shadow-xl"
                    />
                    {/* Enhanced floating label */}
                    {videoUrl && (
                      <div className="absolute -top-3 left-4 bg-gradient-to-r from-purple-500/95 to-indigo-500/95 text-white px-3 py-1 rounded-full text-xs font-medium animate-fade-in backdrop-blur-xl border border-white/30">
                        Video URL Ready
                      </div>
                    )}
                  </div>
                  
                  <div className="flex gap-4">
                    <button
                      onClick={handleSummarize}
                      disabled={!videoUrl?.trim() || isProcessing}
                      className="flex-1 backdrop-blur-3xl bg-white/8 border border-white/25 hover:bg-white/15 text-white py-5 rounded-2xl font-bold shadow-xl hover:shadow-2xl transform hover:scale-[1.02] transition-all duration-500 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none relative overflow-hidden group"
                      aria-label="Summarize YouTube video"
                    >
                      {/* Enhanced button background */}
                      <div className="absolute inset-0 bg-gradient-to-r from-purple-600/40 to-indigo-600/40 translate-x-full group-hover:translate-x-0 transition-transform duration-500" />
                      
                      <div className="relative z-10 flex items-center justify-center">
                        {isProcessing ? (
                          <>
                            <div className="flex space-x-1">
                              <div className="w-2 h-2 bg-white rounded-full animate-bounce" style={{ animationDelay: '0s' }} />
                              <div className="w-2 h-2 bg-white rounded-full animate-bounce" style={{ animationDelay: '0.1s' }} />
                              <div className="w-2 h-2 bg-white rounded-full animate-bounce" style={{ animationDelay: '0.2s' }} />
                            </div>
                            <span className="ml-3">Processing...</span>
                          </>
                        ) : (
                          <>
                            <Zap className="w-6 h-6 mr-3" />
                            Summarize Video
                          </>
                        )}
                      </div>
                    </button>
                    
                    <button
                      onClick={handleClear}
                      disabled={isProcessing}
                      className="px-8 py-5 backdrop-blur-3xl bg-white/8 border border-white/25 hover:bg-white/15 text-white rounded-2xl font-bold transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed hover:scale-105 transform flex items-center justify-center gap-2 shadow-xl"
                      aria-label="Clear input and reset"
                    >
                      <X className="w-5 h-5" />
                      Clear
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Summary Section with Enhanced Glass */}
          <div className={`flex-1 transform transition-all duration-1000 ${mounted ? 'translate-x-0 opacity-100' : 'translate-x-10 opacity-0'}`}>
            {summary && (
              <div className="backdrop-blur-3xl bg-white/5 border border-white/25 rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-700 transform hover:scale-[1.02] overflow-hidden group card-hover-lift animate-fade-in-up relative h-full">
                {/* Enhanced glass gradient overlay */}
                <div className="absolute inset-0 bg-gradient-to-r from-green-500/30 to-blue-500/30 opacity-0 group-hover:opacity-20 transition-opacity duration-500" />
                <div className="absolute inset-0 bg-gradient-to-t from-white/10 via-transparent to-white/5 opacity-100" />
                
                <div className="p-8 relative z-10 flex flex-col h-full">
                  <div className="flex items-center mb-8">
                    <div className="w-12 h-12 bg-gradient-to-br from-green-500/90 to-teal-500/90 rounded-xl flex items-center justify-center mr-4 shadow-xl backdrop-blur-xl border border-white/30">
                      <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                    </div>
                    <div>
                      <h2 className="text-3xl font-bold bg-gradient-to-r from-gray-100 to-gray-300 bg-clip-text text-transparent">Video Summary</h2>
                      <p className="text-white/80 text-sm mt-1">AI-powered content analysis</p>
                    </div>
                  </div>
                  
                  {/* Summary Content with Enhanced Glass */}
                  <div className="prose prose-gray max-w-none flex-1 overflow-y-auto">
                    {summary.split('\n\n').map((paragraph, index) => (
                      <div 
                        key={index} 
                        className="mb-6 p-4 backdrop-blur-xl bg-white/10 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 border border-white/20"
                      >
                        <p className="text-white/90 leading-relaxed text-lg mb-0">
                          {paragraph.split('\n').map((line, lineIndex) => (
                            <span key={lineIndex}>
                              {lineIndex > 0 && <br />}
                              {line.startsWith('•') ? (
                                <span className="flex items-start">
                                  <span className="text-red-400 mr-2">•</span>
                                  <span>{line.substring(1).trim()}</span>
                                </span>
                              ) : (
                                line
                              )}
                            </span>
                          ))}
                        </p>
                      </div>
                    ))}
                  </div>
                  
                  {/* Enhanced Action Buttons */}
                  <div className="mt-10 pt-8 border-t border-white/20">
                    <div className="grid grid-cols-3 gap-4">
                      {[
                        { 
                          action: 'copy', 
                          icon: (
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                            </svg>
                          ), 
                          label: 'Copy', 
                          gradient: 'from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700' 
                        },
                        { 
                          action: 'save', 
                          icon: (
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V2" />
                            </svg>
                          ), 
                          label: 'Save', 
                          gradient: 'from-green-500 to-green-600 hover:from-green-600 hover:to-green-700' 
                        },
                        { 
                          action: 'share', 
                          icon: (
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m9.032 4.026a9.001 9.001 0 01-7.432 0m9.032-4.026A9.001 9.001 0 0112 3c-4.474 0-8.268 3.12-9.032 7.326m0 0A9.001 9.001 0 0012 21c4.474 0 8.268-3.12 9.032-7.326" />
                            </svg>
                          ), 
                          label: 'Share', 
                          gradient: 'from-purple-500 to-purple-600 hover:from-purple-600 hover:to-purple-700' 
                        }
                      ].map((button, index) => (
                        <button 
                          key={button.action}
                          onClick={button.action === 'copy' ? handleCopySummary : button.action === 'save' ? handleSaveSummary : handleShareSummary}
                          data-action={button.action}
                          className={`flex items-center justify-center px-6 py-4 bg-gradient-to-r ${button.gradient} text-white rounded-2xl font-bold shadow-xl hover:shadow-2xl transform hover:scale-105 transition-all duration-500 relative overflow-hidden group opacity-0 animate-fade-in-up button-shine focus-ring backdrop-blur-xl border border-white/20`}
                          style={{ animationDelay: `${0.6 + index * 0.1}s` }}
                          aria-label={`${button.label} video summary`}
                        >
                          {/* Enhanced button background */}
                          <div className="absolute inset-0 bg-gradient-to-r from-white/0 to-white/30 translate-x-full group-hover:translate-x-0 transition-transform duration-500" />
                          
                          <div className="relative z-10 flex items-center justify-center">
                            {button.icon}
                            <span className="ml-2">{button.label}</span>
                          </div>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Empty State with Enhanced Glass */}
            {!summary && (
              <div className="backdrop-blur-3xl bg-white/5 border border-white/25 rounded-3xl shadow-xl p-8 text-center transform transition-all duration-700 hover:scale-[1.02] group relative overflow-hidden h-full">
                {/* Enhanced glass background pattern */}
                <div className="absolute inset-0 bg-gradient-to-br from-gray-50/20 via-white/10 to-gray-100/20 backdrop-blur-xl rounded-3xl" />
                <div className="absolute inset-0 bg-gradient-to-t from-white/10 via-transparent to-white/5 opacity-100" />
                
                {/* Enhanced floating glass elements */}
                <div className="absolute top-4 right-4 w-4 h-4 bg-red-400/30 rounded-full animate-pulse backdrop-blur-sm" />
                <div className="absolute bottom-4 left-4 w-3 h-3 bg-pink-400/30 rounded-full animate-pulse backdrop-blur-sm" style={{ animationDelay: '1s' }} />
                
                <div className="relative z-10 flex flex-col h-full justify-center">
                  <div className="flex justify-center mb-6">
                    <Video className="h-16 w-16 text-purple-400" />
                  </div>
                  <h3 className="text-2xl font-bold bg-gradient-to-r from-gray-100 to-gray-300 bg-clip-text text-transparent mb-4">
                    No Summary Yet
                  </h3>
                  <p className="text-white/80 max-w-md mx-auto mb-8 leading-relaxed">
                    Enter a YouTube video URL and click "Summarize Video" to get started
                  </p>
                  
                  {/* Enhanced Feature Pills */}
                  <div className="flex flex-wrap justify-center gap-3">
                    {[
                      { icon: <Youtube className="h-4 w-4 text-red-500" />, text: 'Supports all YouTube URLs', delay: '0s' },
                      { icon: <Zap className="h-4 w-4 text-yellow-500" />, text: 'Lightning fast processing', delay: '0.1s' },
                      { icon: <Target className="h-4 w-4 text-blue-500" />, text: 'AI-powered analysis', delay: '0.2s' }
                    ].map((feature, index) => (
                      <div 
                        key={index}
                        className="inline-flex items-center space-x-2 px-4 py-2 backdrop-blur-2xl bg-white/15 border border-white/35 rounded-full text-white text-xs font-semibold opacity-0 animate-fade-in-up transform transition-all duration-500 hover:scale-105 hover:bg-white/25 hover:border-white/50 hover:shadow-xl relative overflow-hidden group"
                        style={{ animationDelay: feature.delay }}
                      >
                        {/* Enhanced glass reflection effect */}
                        <div className="absolute inset-0 bg-gradient-to-t from-transparent via-white/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                        
                        {/* Enhanced animated border glow */}
                        <div className="absolute inset-0 rounded-full bg-gradient-to-r from-white/30 via-transparent to-white/30 opacity-0 group-hover:opacity-100 transition-opacity duration-500 animate-pulse" />
                        
                        {/* Enhanced glass shine effect */}
                        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                        
                        <span className="text-sm relative z-10">{feature.icon}</span>
                        <span className="text-xs relative z-10 font-medium">{feature.text}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Enhanced Features Section with Premium Glass */}
        <div className={`mt-20 transform transition-all duration-1000 ${mounted ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
          <div className="text-center mb-16">
            <h2 className="text-5xl font-bold text-white mb-6">
              Why Choose Our Summarizer?
            </h2>
            <p className="text-xl text-white/80 max-w-3xl mx-auto leading-relaxed">
              Experience the future of video content consumption with AI-powered summaries
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                icon: <Zap className="h-8 w-8 text-white" />,
                title: 'Lightning Fast',
                description: 'Get comprehensive summaries in seconds, not minutes. Our AI processes videos instantly to deliver key insights.',
                gradient: 'from-yellow-400 to-orange-500',
                delay: '0s'
              },
              {
                icon: <Target className="h-8 w-8 text-white" />,
                title: 'Accurate Insights',
                description: 'AI-powered analysis captures key points, main topics, and important details with high accuracy and relevance.',
                gradient: 'from-blue-400 to-blue-600',
                delay: '0.2s'
              },
              {
                icon: <BookOpen className="h-8 w-8 text-white" />,
                title: 'Study Friendly',
                description: 'Organized format perfect for learning, revision, and quick reference. Save time while retaining knowledge.',
                gradient: 'from-green-400 to-teal-500',
                delay: '0.4s'
              }
            ].map((feature, index) => (
              <div 
                key={index}
                className="backdrop-blur-3xl bg-white/5 border border-white/25 rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-700 transform hover:scale-[1.02] p-8 text-center group overflow-hidden opacity-0 animate-fade-in-up relative"
                style={{ animationDelay: feature.delay }}
              >
                {/* Enhanced glass gradient overlay */}
                <div className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-20 transition-opacity duration-500`} />
                <div className="absolute inset-0 bg-gradient-to-t from-white/10 via-transparent to-white/5 opacity-100" />
                
                {/* Enhanced glass reflection effect */}
                <div className="absolute inset-0 bg-gradient-to-t from-transparent via-white/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                
                {/* Enhanced animated border glow */}
                <div className="absolute inset-0 rounded-3xl bg-gradient-to-r from-white/20 via-transparent to-white/20 opacity-0 group-hover:opacity-100 transition-opacity duration-500 animate-pulse" />
                
                <div className="relative z-10">
                  <div className={`w-16 h-16 bg-gradient-to-br ${feature.gradient} rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-xl transform transition-all duration-700 group-hover:scale-110 group-hover:rotate-6 backdrop-blur-xl border border-white/30`}>
                    {feature.icon}
                  </div>
                  <h3 className="text-2xl font-bold bg-gradient-to-r from-gray-100 to-gray-300 bg-clip-text text-transparent mb-4 transform transition-all duration-300 group-hover:scale-105">
                    {feature.title}
                  </h3>
                  <p className="text-white/80 leading-relaxed text-base transform transition-all duration-300 group-hover:translate-y-1">
                    {feature.description}
                  </p>
                </div>
                
                {/* Enhanced floating glass elements */}
                <div className="absolute top-4 right-4 w-3 h-3 bg-white/25 rounded-full animate-pulse backdrop-blur-sm" />
                <div className="absolute bottom-4 left-4 w-2 h-2 bg-white/25 rounded-full animate-pulse backdrop-blur-sm" style={{ animationDelay: '1s' }} />
              </div>
            ))}
          </div>
        </div>

        </main>
    </div>
  )
}
